version: '3.8'

services:
  sqlserver: 
    image: mcr.microsoft.com/mssql/server:2022-latest 
    container_name: mssql_server_wpfapp 
    environment:
      ACCEPT_EULA: "Y" 
      SA_PASSWORD: "Password123" 
    
    ports:
      - "1433:1433" 
                    
    volumes:
      - sqlserver_data:/var/opt/mssql 

volumes: 
  sqlserver_data:
    driver: local